### ISSUE TITLE
Project URL is a 404

### ISSUE THREAD

**Issue by SEJeff** [jlelli/sched-deadline-archive#1]
http://www.evidence.eu.com/sched_edf.html

404
Page Not Found!

We are working to fix this problem as soon as possibile.Please visit our website for more information or if you have a questions contact us

**Comment by jlelli** [comment]
Thanks!
We'll fix the problem ASAP.

Regards,
- Juri

**Comment by dfaggioli** [comment]
On Fri, 2012-04-06 at 21:18 -0700, Jeff Schroeder wrote: 

> http://www.evidence.eu.com/sched_edf.html
> 
> 404
> Page Not Found!
> 
> Juri, Claudio, can we do something to fix this? I think either we put
> something back on that URL or we update all our references to that URL
> with something sensible.

Thanks Jeff for reporting this...
Dario

## 

## <<This happens because I choose it to happen!>> (Raistlin Majere)

Dario Faggioli, Ph.D, http://retis.sssup.it/people/faggioli
Senior Software Engineer, Citrix Systems R&D Ltd., Cambridge (UK)

**Comment by dfaggioli** [comment]
Il 07/04/2012 12:11, Dario Faggioli ha scritto:

> On Fri, 2012-04-06 at 21:18 -0700, Jeff Schroeder wrote:
> 
> > http://www.evidence.eu.com/sched_edf.html
> > 
> > 404
> > Page Not Found!
> > 
> > Juri, Claudio, can we do something to fix this? I think either we put
> > something back on that URL or we update all our references to that URL
> > with something sensible.

The right link now is http://www.evidence.eu.com/sched_deadline.html 
(since the project has changed name), but we are going to restore this 
link as well.

Many thanks,

```
Claudio
```
