### ISSUE TITLE
SCHED_DEADLINE will freeze the system on a kernel patched with PREEMP_RT

### ISSUE THREAD

**Issue by facontidavide** [jlelli/sched-deadline-archive#10]
The title says it all. I used rt-app to create a periodic task and my PC freezes completely when the kernel used is patched with PREEMPT_RT.

Any clues? Any suggestion about how I can debug this problem?

**Comment by claudioscordino** [comment]
How much bandwidth does the SCHED_DEADLINE taskset consume ? 100% ?

**Comment by facontidavide** [comment]
I launched it with 33%

rt-app -t 3000:1000:d

On Thu, Apr 24, 2014 at 12:35 PM, Claudio notifications@github.com wrote:

> How much bandwidth does the SCHED_DEADLINE taskset consume ? 100% ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/jlelli/sched-deadline/issues/10#issuecomment-41265554
> .

## 

## Davide Faconti

## _Icarus Technology SLU http://www.icarustechnology.com_

_NIF_: B64096571

## tel. +34666722156

Rbla de Catalunya 38, 8ª planta

## 08007, Barcelona, Spain

www.icarustechnology.com

**Comment by claudioscordino** [comment]
Which kernel are you using ? Any way of trying 3.14 ? 
(which already has SCHED_DEADLINE merged)

**Comment by facontidavide** [comment]
I am trying kernel 3.14... otherwise SCHED_DEADLINE won't be there ;)

The description of what I did can be found here:
http://www.icarusrobotics.com/?p=1187
You will find debian packages to install yourself the kernel I am using on
your Ubuntu machine (if you have one).
But, in short, I used
- kernel _3.14.0_
- PREEMP_RT patch _patch-3.14.0-rt1_
  
  ᐧ

On Thu, Apr 24, 2014 at 12:40 PM, Claudio notifications@github.com wrote:

> Which kernel are you using ? Any way of trying 3.14 ?
> (which already has SCHED_DEADLINE merged)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jlelli/sched-deadline/issues/10#issuecomment-41265960
> .

## 

## Davide Faconti

## _Icarus Technology SLU http://www.icarustechnology.com_

_NIF_: B64096571

## tel. +34666722156

Rbla de Catalunya 38, 8ª planta

## 08007, Barcelona, Spain

www.icarustechnology.com

**Comment by jlelli** [comment]
Saw the same here. 3.14-rt1 has problems running SCHED_DEADLINE tasks
(note that it is the first release on top of 3.14). It is not an rt-app
problem, though. Hope to find out a solution soon.

Thanks!
