### ISSUE TITLE
Please rename project to SCHED_EDF 

### ISSUE THREAD

**Issue by pavlinux** [jlelli/sched-deadline-archive#5]
People confused with I/O Scheduler  (IOSCHED_DEADLINE) 

:)

**Comment by claudioscordino** [comment]
Actually, SCHED_EDF was the initial name, and it has been changed to SCHED_DEADLINE upon request of the kernel community itself (see https://lkml.org/lkml/2009/9/22/214).

**Comment by pavlinux** [comment]
Heh, funny :)
