### ISSUE TITLE
Documentation uses wrong percentage of bandwdith

### ISSUE THREAD

**Issue by jtdaugherty** [jlelli/sched-deadline-archive#6]
Hi,

The documentation states that a runtime of 500000 usec and a period of 1000000 usec yields a bandwidth limit of 5%:

https://github.com/jlelli/sched-deadline/blob/mainline-dl/Documentation/scheduler/sched-deadline.txt#L140

But I'm pretty sure that equals 50%, not 5%.  5% would be 50000 usec runtime, wouldn't it?

**Comment by jlelli** [comment]
You were right. But, the bandwidth admission control is totally changed now :). Check the documentation on sched-dl-V7 branch.
Thanks for your post, though.

**Comment by jtdaugherty** [comment]
Okay. I'm using an older version and it was wrong in my docs, so I followed the mistake here. :) Thanks!
